module.exports = {
  "v2-static-analysis-testing-javascript-applications": {
    "javascript-run-multiple-npm-scripts-in-parallel-with-npm-run-all":
      "https://github.com/kentcdodds/static-testing-tools/compare/tjs/step-12...tjs/step-13",
    "javascript-auto-format-all-files-and-validate-relevant-files-in-a-precommit-script-with-lint-staged":
      "https://github.com/kentcdodds/static-testing-tools/compare/tjs/step-11...tjs/step-12",
    "javascript-validate-code-in-a-pre-commit-git-hook-with-husky-2d052239":
      "https://github.com/kentcdodds/static-testing-tools/compare/tjs/step-10...tjs/step-11",
    "javascript-make-eslint-support-typescript-files":
      "https://github.com/kentcdodds/static-testing-tools/compare/tjs/step-09...tjs/step-10",
    "javascript-avoid-common-errors-by-installing-and-configuring-typescript":
      "https://github.com/kentcdodds/static-testing-tools/compare/tjs/step-08...tjs/step-09",
    "javascript-validate-all-files-are-properly-formatted-with-prettier":
      "https://github.com/kentcdodds/static-testing-tools/compare/tjs/step-06...tjs/step-07",
    "javascript-disable-unnecessary-eslint-stylistic-rules-with-eslint-config-prettier":
      "https://github.com/kentcdodds/static-testing-tools/compare/tjs/step-05...tjs/step-06",
    "javascript-use-the-prettier-extension-for-vscode": "NO-CODE",
    "eslint-configure-prettier":
      "https://github.com/kentcdodds/static-testing-tools/compare/tjs/step-04...tjs/step-05",
    "javascript-format-code-by-installing-and-running-prettier-5b753fd5":
      "https://github.com/kentcdodds/static-testing-tools/compare/tjs/step-03...tjs/step-04",
    "eslint-run-eslint-with-npm-scripts":
      "https://github.com/kentcdodds/static-testing-tools/compare/tjs/step-02...tjs/step-03",
    "eslint-use-pre-built-eslint-configuration-using-extends":
      "https://github.com/kentcdodds/static-testing-tools/compare/tjs/step-01...tjs/step-02",
    "eslint-use-the-eslint-extension-for-vscode": "NO-CODE",
    "javascript-lint-javascript-by-configuring-and-running-eslint":
      "https://github.com/kentcdodds/static-testing-tools/compare/tjs/step-00...tjs/step-01"
  },
  "v2-install-configure-and-script-cypress-for-javascript-web-applications": {
    "cypress-install-react-devtools-with-cypress":
      "https://github.com/kentcdodds/jest-cypress-react-babel-webpack/compare/tjs/cypress-16...tjs/cypress-17",
    "cypress-combine-custom-cypress-commands-into-a-single-custom-command":
      "https://github.com/kentcdodds/jest-cypress-react-babel-webpack/compare/tjs/cypress-15...tjs/cypress-16",
    "cypress-use-a-custom-cypress-command-to-login-as-a-user":
      "https://github.com/kentcdodds/jest-cypress-react-babel-webpack/compare/tjs/cypress-14...tjs/cypress-15",
    "cypress-use-cy-request-from-cypress-to-authenticate-as-a-new-user":
      "https://github.com/kentcdodds/jest-cypress-react-babel-webpack/compare/tjs/cypress-13...tjs/cypress-14",
    "cypress-run-tests-as-an-authenticated-user-with-cypress":
      "https://github.com/kentcdodds/jest-cypress-react-babel-webpack/compare/tjs/cypress-12...tjs/cypress-13",
    "cypress-use-custom-cypress-command-for-reusable-assertions":
      "https://github.com/kentcdodds/jest-cypress-react-babel-webpack/compare/tjs/cypress-11...tjs/cypress-12",
    "cypress-keep-tests-isolated-and-focused-with-custom-cypress-commands":
      "https://github.com/kentcdodds/jest-cypress-react-babel-webpack/compare/tjs/cypress-10...tjs/cypress-11",
    "cypress-create-a-user-with-cy-request-from-cypress":
      "https://github.com/kentcdodds/jest-cypress-react-babel-webpack/compare/tjs/cypress-09...tjs/cypress-10",
    "cypress-test-user-login-with-cypress-fa061295":
      "https://github.com/kentcdodds/jest-cypress-react-babel-webpack/compare/tjs/cypress-08...tjs/cypress-09",
    "cypress-simulate-http-errors-in-cypress-tests":
      "https://github.com/kentcdodds/jest-cypress-react-babel-webpack/compare/tjs/cypress-07...tjs/cypress-08",
    "cypress-cypress-driven-development":
      "https://github.com/kentcdodds/jest-cypress-react-babel-webpack/compare/tjs/cypress-06...tjs/cypress-07",
    "cypress-test-user-registration-with-cypress":
      "https://github.com/kentcdodds/jest-cypress-react-babel-webpack/compare/tjs/cypress-05...tjs/cypress-06",
    "cypress-debug-a-test-with-cypress":
      "https://github.com/kentcdodds/jest-cypress-react-babel-webpack/tree/tjs/cypress-05",
    "cypress-script-cypress-for-local-development-and-continuous-integration":
      "https://github.com/kentcdodds/jest-cypress-react-babel-webpack/compare/tjs/cypress-04...tjs/cypress-05",
    "cypress-installing-cypress-testing-library":
      "https://github.com/kentcdodds/jest-cypress-react-babel-webpack/compare/tjs/cypress-03...tjs/cypress-04",
    "cypress-configure-cypress-in-cypress-json":
      "https://github.com/kentcdodds/jest-cypress-react-babel-webpack/compare/tjs/cypress-02...tjs/cypress-03",
    "cypress-write-the-first-cypress-test":
      "https://github.com/kentcdodds/jest-cypress-react-babel-webpack/compare/tjs/cypress-01...tjs/cypress-02",
    "jest-install-and-run-cypress":
      "https://github.com/kentcdodds/jest-cypress-react-babel-webpack/compare/tjs/cypress-00...tjs/cypress-01"
  },
  "v2-configure-jest-for-testing-javascript-applications": {
    "jest-run-only-relevant-jest-tests-on-git-commit-to-avoid-breakages":
      "https://github.com/kentcdodds/jest-cypress-react-babel-webpack/compare/tjs/jest-22...tjs/jest-23",
    "jest-filter-which-tests-are-run-with-typeahead-support-in-jest-watch-mode":
      "https://github.com/kentcdodds/jest-cypress-react-babel-webpack/compare/tjs/jest-21...tjs/jest-22",
    "jest-test-specific-projects-in-jest-watch-mode-with-jest-watch-select-projects":
      "https://github.com/kentcdodds/jest-cypress-react-babel-webpack/compare/tjs/jest-20...tjs/jest-21",
    "jest-run-eslint-with-jest-using-jest-runner-eslint":
      "https://github.com/kentcdodds/jest-cypress-react-babel-webpack/compare/tjs/jest-19...tjs/jest-20",
    "jest-support-running-multiple-configurations-with-jest-s-projects-feature":
      "https://github.com/kentcdodds/jest-cypress-react-babel-webpack/compare/tjs/jest-18...tjs/jest-19",
    "jest-run-tests-with-a-different-configuration-using-jest-s-config-flag-and-testmatch-option":
      "https://github.com/kentcdodds/jest-cypress-react-babel-webpack/compare/tjs/jest-17...tjs/jest-18",
    "jest-run-jest-watch-mode-by-default-locally-with-is-ci-cli":
      "https://github.com/kentcdodds/jest-cypress-react-babel-webpack/compare/tjs/jest-16...tjs/jest-17",
    "jest-report-jest-test-coverage-to-codecov-through-travisci-6b8076a6":
      "https://github.com/kentcdodds/jest-cypress-react-babel-webpack/compare/tjs/jest-15...tjs/jest-16",
    "jest-set-a-code-coverage-threshold-in-jest-to-maintain-code-coverage-levels":
      "https://github.com/kentcdodds/jest-cypress-react-babel-webpack/compare/tjs/jest-14...tjs/jest-15",
    "jest-analyze-jest-code-coverage-reports":
      "https://gist.github.com/kentcdodds/3f57448c47c404e12200815048b1cc01",
    "jest-configure-jest-to-report-code-coverage-on-project-files":
      "https://github.com/kentcdodds/jest-cypress-react-babel-webpack/compare/tjs/jest-13...tjs/jest-14",
    "jest-step-through-code-in-jest-using-the-node-js-debugger-and-chrome-devtools":
      "https://github.com/kentcdodds/jest-cypress-react-babel-webpack/compare/tjs/jest-12...tjs/jest-13",
    "jest-use-jest-watch-mode-to-speed-up-development":
      "https://github.com/kentcdodds/jest-cypress-react-babel-webpack/compare/tjs/jest-11...tjs/jest-12",
    "jest-support-a-test-utilities-file-with-jest-moduledirectories":
      "https://github.com/kentcdodds/jest-cypress-react-babel-webpack/compare/tjs/jest-10...tjs/jest-11",
    "jest-configure-jest-to-run-setup-for-all-tests-with-jest-setupfilesafterenv":
      "https://github.com/kentcdodds/jest-cypress-react-babel-webpack/compare/tjs/jest-08...tjs/jest-09",
    "jest-support-custom-module-resolution-with-jest-moduledirectories":
      "https://github.com/kentcdodds/jest-cypress-react-babel-webpack/compare/tjs/jest-07...tjs/jest-08",
    "jest-test-an-emotion-styled-ui-with-custom-jest-snapshot-serializers":
      "https://github.com/kentcdodds/jest-cypress-react-babel-webpack/compare/tjs/jest-06...tjs/jest-07",
    "jest-generate-a-serializable-value-with-jest-snapshots":
      "https://github.com/kentcdodds/jest-cypress-react-babel-webpack/compare/tjs/jest-05...tjs/jest-06",
    "jest-support-using-webpack-css-modules-with-jest":
      "https://github.com/kentcdodds/jest-cypress-react-babel-webpack/compare/tjs/jest-04...tjs/jest-05",
    "jest-support-importing-css-files-with-jest-s-modulenamemapper":
      "https://github.com/kentcdodds/jest-cypress-react-babel-webpack/compare/tjs/jest-03...tjs/jest-04",
    "jest-configure-jest-s-test-environment-for-testing-node-or-browser-code":
      "https://github.com/kentcdodds/jest-cypress-react-babel-webpack/compare/tjs/jest-02...tjs/jest-03",
    "jest-compile-modules-with-babel-in-jest-tests":
      "https://github.com/kentcdodds/jest-cypress-react-babel-webpack/compare/tjs/jest-01...tjs/jest-02",
    "jest-install-and-run-jest-b6337c96":
      "https://github.com/kentcdodds/jest-cypress-react-babel-webpack/compare/tjs/jest-00...tjs/jest-01"
  }
};
